# Generated by Django 3.0.4 on 2020-03-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotword', models.CharField(max_length=100)),
                ('hotword2', models.CharField(max_length=100)),
                ('output', models.CharField(max_length=1000)),
                ('output2', models.CharField(max_length=1000)),
                ('output3', models.CharField(max_length=1000)),
                ('Clientname', models.CharField(max_length=50)),
            ],
        ),
    ]
