# Generated by Django 3.0.4 on 2020-03-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_auto_20200326_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='Clientname',
        ),
    ]
